export const items = [
  {
    id: 1,
    name: "Organic Tomatoes",
    category: "Organic Veggies",
    price: 55,
    unit: "1 kg",
    image: `${import.meta.env.BASE_URL}/tomaotoes.jpg`,
    stock: 45,
    rating: 4.7,
  },
  {
    id: 2,
    name: "Organic Spinach",
    category: "Organic Veggies",
    price: 30,
    unit: "250 g",
    image: `${import.meta.env.BASE_URL}/spinach.jpg`,
    stock: 30,
    rating: 3.9,
  },
  {
    id: 3,
    name: "Organic Broccoli",
    category: "Organic Veggies",
    price: 80,
    unit: "500 g",
    image: `${import.meta.env.BASE_URL}/broccoli.jpg`,
    stock: 25,
    rating: 4.2,
  },
  {
    id: 4,
    name: "Organic Carrots",
    category: "Organic Veggies",
    price: 45,
    unit: "1 kg",
    image: `${import.meta.env.BASE_URL}/carrot.jpg`,
    stock: 60,
    rating: 4.1,
  },
  {
    id: 5,
    name: "Organic Cauliflower",
    category: "Organic Veggies",
    price: 60,
    unit: "1 pc",
    image: `${import.meta.env.BASE_URL}/cauliflower.jpg`,
    stock: 15,
    rating: 4.8,
  },
  {
    id: 6,
    name: "Organic Cucumbers",
    category: "Organic Veggies",
    price: 35,
    unit: "2 pcs",
    image: `${import.meta.env.BASE_URL}/Cucumbers.jpg`,
    stock: 55,
    rating: 3.7,
  },
  {
    id: 7,
    name: "Fresh Apples",
    category: "Fresh Fruits",
    price: 120,
    unit: "1 kg",
    image: `${import.meta.env.BASE_URL}/apple.jpg`,
    stock: 75,
    rating: 4.9,
  },
  {
    id: 8,
    name: "Fresh Oranges",
    category: "Fresh Fruits",
    price: 90,
    unit: "1 kg",
    image: `${import.meta.env.BASE_URL}/orange.jpg`,
    stock: 65,
    rating: 4.0,
  },
  {
    id: 9,
    name: "Fresh Grapes",
    category: "Fresh Fruits",
    price: 150,
    unit: "500 g",
    image: `${import.meta.env.BASE_URL}/green-grape.png`,
    stock: 40,
    rating: 4.6,
  },
  {
    id: 10,
    name: "Fresh Watermelon",
    category: "Fresh Fruits",
    price: 70,
    unit: "1 pc",
    image: `${import.meta.env.BASE_URL}/watermelon.jpg`,
    stock: 20,
    rating: 4.2,
  },
  {
    id: 11,
    name: "Fresh Pears",
    category: "Fresh Fruits",
    price: 110,
    unit: "500 g",
    image: `${import.meta.env.BASE_URL}/pears.jpg`,
    stock: 35,
    rating: 4.4,
  },
  {
    id: 12,
    name: "Fresh Kiwis",
    category: "Fresh Fruits",
    price: 130,
    unit: "4 pcs",
    image: `${import.meta.env.BASE_URL}/kiwi.jpg`,
    stock: 28,
    rating: 3.8,
  },
  {
    id: 13,
    name: "Coca-Cola Classic",
    category: "Cold Drinks",
    price: 30,
    unit: "300 ml can",
    image: `${import.meta.env.BASE_URL}/coco_cola.jpeg`,
    stock: 100,
    rating: 4.3,
  },
  {
    id: 14,
    name: "Sprite",
    category: "Cold Drinks",
    price: 30,
    unit: "300 ml can",
    image: `${import.meta.env.BASE_URL}/sprite.jpg`,
    stock: 95,
    rating: 4.1,
  },
  {
    id: 15,
    name: "Pepsi",
    category: "Cold Drinks",
    price: 30,
    unit: "300 ml can",
    image: `${import.meta.env.BASE_URL}/pepsi.jpeg`,
    stock: 80,
    rating: 4.0,
  },
  {
    id: 16,
    name: "Lipton Iced Tea",
    category: "Cold Drinks",
    price: 45,
    unit: "500 ml bottle",
    image: `${import.meta.env.BASE_URL}/lipton iced tea.jpg`,
    stock: 70,
    rating: 3.9,
  },
  {
    id: 17,
    name: "Minute Maid Orange Juice",
    category: "Cold Drinks",
    price: 99,
    unit: "1 L carton",
    image: `${import.meta.env.BASE_URL}/minute maid orange juice.jpg`,
    stock: 50,
    rating: 4.7,
  },
  {
    id: 18,
    name: "Red Bull",
    category: "Cold Drinks",
    price: 120,
    unit: "250 ml can",
    image: `${import.meta.env.BASE_URL}/red bull.jpg`,
    stock: 65,
    rating: 4.5,
  },
  {
    id: 19,
    name: "Nestle Maggi Noodles",
    category: "Instant Food",
    price: 20,
    unit: "70 g pack",
    image: `${import.meta.env.BASE_URL}/maggi_image.png`,
    stock: 200,
    rating: 4.0,
  },
  {
    id: 20,
    name: "Top Ramen Noodles",
    category: "Instant Food",
    price: 18,
    unit: "70 g pack",
    image: `${import.meta.env.BASE_URL}/ramen maggi.jpg`,
    stock: 180,
    rating: 3.9,
  },
  {
    id: 21,
    name: "MTR Ready-to-Eat Biryani",
    category: "Instant Food",
    price: 95,
    unit: "300 g pack",
    image: `${import.meta.env.BASE_URL}/MTR_BIRYANIMASALA_15g_Fop_1024x1024@2x.webp`,
    stock: 40,
    rating: 4.4,
  },
  {
    id: 22,
    name: "Knorr Instant Soup",
    category: "Instant Food",
    price: 45,
    unit: "50 g sachet",
    image: `${import.meta.env.BASE_URL}/knorr_soup.jpg`,
    stock: 75,
    rating: 4.1,
  },
  {
    id: 23,
    name: "Haldiram's Dal Biji",
    category: "Instant Food",
    price: 60,
    unit: "150 g pack",
    image: `${import.meta.env.BASE_URL}/haldiram dal biji.jpg`,
    stock: 90,
    rating: 4.2,
  },
  {
    id: 24,
    name: "Amul Milk",
    category: "Dairy Products",
    price: 32,
    unit: "500 ml pouch",
    image: `${import.meta.env.BASE_URL}/amul milk.jpg`,
    stock: 120,
    rating: 4.0,
  },
  {
    id: 25,
    name: "Nestlé Curd",
    category: "Dairy Products",
    price: 45,
    unit: "400 g cup",
    image: `${import.meta.env.BASE_URL}/nestle curd.jpg`,
    stock: 80,
    rating: 3.8,
  },
  {
    id: 26,
    name: "Amul Butter",
    category: "Dairy Products",
    price: 50,
    unit: "100 g block",
    image: `${import.meta.env.BASE_URL}/amul butter.jpg`,
    stock: 65,
    rating: 4.5,
  },
  {
    id: 27,
    name: "Britannia Cheese Slices",
    category: "Dairy Products",
    price: 120,
    unit: "200 g pack",
    image: `${import.meta.env.BASE_URL}/britannia cheese.jpg`,
    stock: 50,
    rating: 4.6,
  },
  {
    id: 28,
    name: "Mother Dairy Paneer",
    category: "Dairy Products",
    price: 105,
    unit: "200 g pack",
    image: `${import.meta.env.BASE_URL}/mother-dairy-malai-paneer.webp`,
    stock: 45,
    rating: 4.3,
  },
  {
    id: 29,
    name: "Britannia Whole Wheat Bread",
    category: "Bakery & Breads",
    price: 40,
    unit: "400 g loaf",
    image: `${import.meta.env.BASE_URL}/Britannia Whole Wheat Bread.jpg`,
    stock: 70,
    rating: 4.2,
  },
  {
    id: 30,
    name: "Modern White Bread",
    category: "Bakery & Breads",
    price: 35,
    unit: "400 g loaf",
    image: `${import.meta.env.BASE_URL}/modern white bread.jpg`,
    stock: 60,
    rating: 3.9,
  },
  {
    id: 31,
    name: "Parle-G Biscuits",
    category: "Bakery & Breads",
    price: 10,
    unit: "80 g pack",
    image: `${import.meta.env.BASE_URL}/Parle-G Biscuits.jpg`,
    stock: 250,
    rating: 4.1,
  },
  {
    id: 32,
    name: "Oreo Cookies",
    category: "Bakery & Breads",
    price: 30,
    unit: "120 g pack",
    image: `${import.meta.env.BASE_URL}/oreo cookies.jpg`,
    stock: 150,
    rating: 4.4,
  },
  {
    id: 33,
    name: "Britannia Good Day Cookies",
    category: "Bakery & Breads",
    price: 25,
    unit: "100 g pack",
    image: `${import.meta.env.BASE_URL}/Britannia Good Day Cookies.jpg`,
    stock: 180,
    rating: 3.9,
  },
  {
    id: 34,
    name: "Rusk",
    category: "Bakery & Breads",
    price: 35,
    unit: "200 g pack",
    image: `${import.meta.env.BASE_URL}/rusk.jpg`,
    stock: 90,
    rating: 4.0,
  },
  {
    id: 35,
    name: "Aashirvaad Atta",
    category: "Grains & Cereals",
    price: 250,
    unit: "5 kg bag",
    image: `${import.meta.env.BASE_URL}/aashirvaad atta.jpg`,
    stock: 50,
    rating: 4.5,
  },
  {
    id: 36,
    name: "India Gate Basmati Rice",
    category: "Grains & Cereals",
    price: 300,
    unit: "1 kg bag",
    image: `${import.meta.env.BASE_URL}/india gate basmati rice.webp`,
    stock: 40,
    rating: 4.5,
  },
  {
    id: 37,
    name: "Kellogg's Corn Flakes",
    category: "Grains & Cereals",
    price: 180,
    unit: "300 g box",
    image: `${import.meta.env.BASE_URL}/corn flakes.jpg`,
    stock: 60,
    rating: 4.1,
  },
  {
    id: 38,
    name: "Quaker Oats",
    category: "Grains & Cereals",
    price: 150,
    unit: "500 g pack",
    image: `${import.meta.env.BASE_URL}/quaker oats.jpg`,
    stock: 55,
    rating: 4.2,
  },
  {
    id: 39,
    name: "Rajma",
    category: "Grains & Cereals",
    price: 90,
    unit: "500 g pack",
    image: `${import.meta.env.BASE_URL}/rajma.webp`,
    stock: 70,
    rating: 4.0,
  },
  {
    id: 40,
    name: "Moong Dal",
    category: "Grains & Cereals",
    price: 85,
    unit: "500 g pack",
    image: `${import.meta.env.BASE_URL}/moong dal.webp`,
    stock: 65,
    rating: 4.3,
  },
  {
    id: 41,
    name: "Toor Dal",
    category: "Grains & Cereals",
    price: 100,
    unit: "500 g pack",
    image: `${import.meta.env.BASE_URL}/toor dal.webp`,
    stock: 50,
    rating: 4.1,
  },
  {
    id: 42,
    name: "Chana Dal",
    category: "Grains & Cereals",
    price: 95,
    unit: "500 g pack",
    image: `${import.meta.env.BASE_URL}/chana dal.webp`,
    stock: 60,
    rating: 3.8,
  },
];
